name: Process Artifact

on:
  workflow_run:   
    workflows: ["Build and Store Artifact"] 
    types: 
      - completed  

jobs:
  dummy_job:   # Job to resolve the error
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder step
        run: echo "This job ensures workflow validity"

  process_artifact:  # This job actually processes the artifact
    runs-on: ubuntu-latest
    needs: [build, dummy_job]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact 
      - name: Process the artifact
        run: | 
          artifactData=$(cat data.json)
          timestamp=$(echo $artifactData | jq '.timestamp')
          message=$(echo $artifactData | jq '.message')
          echo "Artifact generated at: $timestamp"
          echo "Message from artifact: $message"
